### ISSUE TITLE
Can you make icons into Widgets in DestinationModel?

### ISSUE THREAD

**Issue by saklanmazozgur** [egortabula/material3_layout#3]
Hi there are icon and selectedIcon in DestinationModel. Making them widgets will give you the freedom to add different icon sets or other things like images. Is this upgrade possible?

**Comment by egortabula** [comment]
Ok, I will change it to Widget type

**Comment by saklanmaz** [comment]
Thank you I would like to submit a pull request but I was not available at the time.

**Comment by egortabula** [comment]
I updated it already, but I didn't push it to pub.dev currently

**Comment by egortabula** [comment]
Hi! Version is updated on pub.dev.
